{
 "title": "IMPRESSORAS  ADM",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "\n<CENTER><h1><b> ADMINISTRATIVO  </b></h1></CENTER>\n\n\n\n"
  },
  {
   "title": "COMPRAS",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "targets": [
    {
     "application": { "filter": "Informacoes do Tonner Black" },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M5360 - COMPRAS" },
     "item": {
      "filter": "Nivel do Black Toner Cartridge S/N:CRUM-19011867373 ( Porcentagem)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CONTAS A PAGAR",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 2 },
   "targets": [
    {
     "application": { "filter": "Informacoes do Tonner Black" },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M5360 - CONTAS A PAGAR" },
     "item": {
      "filter": "Nivel do Black Toner Cartridge S/N:CRUM-18022826959 ( Porcentagem)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "FISCAL CONTABILIDADE",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 2 },
   "targets": [
    {
     "application": { "filter": "Informacoes do Tonner Black" },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M5360 - FISCAL CONTABILIDADE" },
     "item": {
      "filter": "Nivel do Black Toner Cartridge S/N:CRUM-18022693871 ( Porcentagem)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RH PRETO E BRANCO",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 2 },
   "targets": [
    {
     "application": { "filter": "Informacoes do Tonner Black" },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M5360 - RH PRETO E BRANCO" },
     "item": {
      "filter": "Nivel do Black Toner Cartridge S/N:CRUM-19011866438 ( Porcentagem)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SESMT",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
   "targets": [
    {
     "application": { "filter": "Informacoes do Tonner Black" },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M5360 - SESMT" },
     "item": {
      "filter": "Nivel do Black Toner Cartridge S/N:CRUM-19012851680 ( Porcentagem)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Disponibilidade do Equipamento"
     },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M5360 - COMPRAS" },
     "item": { "filter": "PingStatus" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 5
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Disponibilidade do Equipamento"
     },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M5360 - CONTAS A PAGAR" },
     "item": { "filter": "PingStatus" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 5
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Disponibilidade do Equipamento"
     },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M5360 - FISCAL CONTABILIDADE" },
     "item": { "filter": "PingStatus" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 5
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Disponibilidade do Equipamento"
     },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M5360 - RH PRETO E BRANCO" },
     "item": { "filter": "PingStatus" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 5
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Disponibilidade do Equipamento"
     },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M5360 - SESMT" },
     "item": { "filter": "PingStatus" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 5
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Paginas Impressas"
     },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M5360 - COMPRAS" },
     "item": { "filter": "Paginas Impressas Total" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 5
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Paginas Impressas"
     },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M5360 - CONTAS A PAGAR" },
     "item": { "filter": "Paginas Impressas Total" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 5
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Paginas Impressas"
     },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M5360 - FISCAL CONTABILIDADE" },
     "item": { "filter": "Paginas Impressas Total" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 5
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Paginas Impressas"
     },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M5360 - RH PRETO E BRANCO" },
     "item": { "filter": "Paginas Impressas Total" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 5
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Paginas Impressas"
     },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M5360 - SESMT" },
     "item": { "filter": "Paginas Impressas Total" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 5
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes do Fusor da Impressora"
     },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M5360 - COMPRAS" },
     "item": {
      "filter": "Tempo de Vida Restante no Fusor"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 5
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes do Fusor da Impressora"
     },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M5360 - CONTAS A PAGAR" },
     "item": {
      "filter": "Tempo de Vida Restante no Fusor"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 5
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes do Fusor da Impressora"
     },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M5360 - FISCAL CONTABILIDADE" },
     "item": {
      "filter": "Tempo de Vida Restante no Fusor"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 5
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes do Fusor da Impressora"
     },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M5360 - RH PRETO E BRANCO" },
     "item": {
      "filter": "Tempo de Vida Restante no Fusor"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 5
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes do Fusor da Impressora"
     },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M5360 - SESMT" },
     "item": {
      "filter": "Tempo de Vida Restante no Fusor"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 5
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Número de série do dispositivo" },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M5360 - COMPRAS" },
     "item": { "filter": "Número de série" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 5
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Número de série do dispositivo" },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M5360 - CONTAS A PAGAR" },
     "item": { "filter": "Número de série" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 5
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Número de série do dispositivo" },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M5360 - FISCAL CONTABILIDADE" },
     "item": { "filter": "Número de série" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 5
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Número de série do dispositivo" },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M5360 - RH PRETO E BRANCO" },
     "item": { "filter": "Número de série" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 5
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Número de série do dispositivo" },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M5360 - SESMT" },
     "item": { "filter": "Número de série" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 5
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 },
   "content": "\n<CENTER><h1><b>DIRETORIA COLORIDA  </b></h1></CENTER>\n\n\n\n"
  },
  {
   "title": "BLACK",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 19 },
   "targets": [
    {
     "application": { "filter": "Informacoes do Tonner Black" },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M4010 - DIRETORIA" },
     "item": {
      "filter": "Nivel do Black Toner Cartridge S/N:CRUM-181116A0670 ( Porcentagem)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CYAN",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 19 },
   "targets": [
    {
     "application": { "filter": "Informacoes do Tonner Cyan" },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M4010 - DIRETORIA" },
     "item": {
      "filter": "Nivel do Cyan Toner Cartridge S/N:CRUM-181116A05A4 ( Porcentagem)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "MAGENTA",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 19 },
   "targets": [
    {
     "application": { "filter": "Informacoes do Tonner Magenta" },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M4010 - DIRETORIA" },
     "item": {
      "filter": "Nivel do Magenta Toner Cartridge S/N:CRUM-181116A039F ( Porcentagem)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "YELLOW",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 19 },
   "targets": [
    {
     "application": { "filter": "Informacoes do Tonner Yellow" },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M4010 - DIRETORIA" },
     "item": {
      "filter": "Nivel do Yellow Toner Cartridge S/N:CRUM-181116A03B6 ( Porcentagem)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 16, "x": 3, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Disponibilidade do Equipamento"
     },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M4010 - DIRETORIA" },
     "item": { "filter": "PingStatus" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 5
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 16, "x": 3, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Paginas Impressas"
     },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M4010 - DIRETORIA" },
     "item": { "filter": "Paginas Impressas Total" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 5
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 16, "x": 3, "y": 29 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes do Fusor da Impressora"
     },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M4010 - DIRETORIA" },
     "item": {
      "filter": "Tempo de Vida Restante no Fusor"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 5
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 16, "x": 3, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Número de série do dispositivo" },
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "M4010 - DIRETORIA" },
     "item": { "filter": "Número de série" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 5
     }
    }
   ]
  }
 ]
}